#!/bin/bash
# reference: https://github.com/google/macops-keychainminder/blob/master/Package/postinstall

# Load Daemon
[[ $3 != "/" ]] && exit 0
/bin/launchctl load /Library/LaunchDaemons/com.objective-see.ransomwhere.plist

exit 0
