//
//  Queue.m
//  RansomWhere
//
//  Created by Patrick Wardle on 9/26/14.
//  Copyright © 2016 Objective-See. All rights reserved.
//

//TODO: https://developer.apple.com/library/mac/qa/qa1419/_index.html to increase stack size if too many threads?
//TODO: ignore  /Users/patrickw/Library/Saved Application State/com.apple.Console.savedState/window_2.data? 

#import "main.h"
#import "Event.h"
#import "Queue.h"
#import "Consts.h"
#import "Process.h"
#import "Logging.h"
#import "Utilities.h"

@implementation Queue

@synthesize eventQueue;
@synthesize allowedProcs;
@synthesize queueCondition;
@synthesize disallowedProcs;

//init
// ->alloc & queue thead
-(id)init
{
    //init super
    self = [super init];
    if(nil != self)
    {
        //init queue
        eventQueue = [NSMutableArray array];
 
        //init empty condition
        queueCondition = [[NSCondition alloc] init];
 
        //alloc for 'user-allowed' processes
        allowedProcs = [NSMutableDictionary dictionary];
        
        //alloc for 'user-disallowed' processes
        disallowedProcs = [NSMutableDictionary dictionary];
        
        //spin up thread to watch/process queue
        [NSThread detachNewThreadSelector:@selector(dequeue:) toTarget:self withObject:nil];
    }
    
    return self;
}

//add an object to the queue
-(void)enqueue:(id)anObject
{
    //lock
    [self.queueCondition lock];
    
    //add to queue
    [self.eventQueue enqueue:anObject];
    
    //signal
    [self.queueCondition signal];
    
    //unlock
    [self.queueCondition unlock];
    
    return;
}

//dequeue
// ->forever, process events from queue
-(void)dequeue:(id)threadParam
{
    //watch event
    Event* event = nil;

    //for ever
    while(YES)
    {
        //pool
        @autoreleasepool {
            
        //lock queue
        [self.queueCondition lock];
        
        //wait while queue is empty
        while(YES == [self.eventQueue empty])
        {
            //wait
            [self.queueCondition wait];
        }
        
        //item is in queue!
        // ->grab it, then process
        event = [eventQueue dequeue];
            
        //unlock
        [self.queueCondition unlock];
            
        //create thread to process event
        [NSThread detachNewThreadSelector:@selector(processEvent:) toTarget:self withObject:event];
        
        }//pool
        
    }//loop: foreverz process queue
        
    return;
}

//thread method
// ->process event off queue
-(void)processEvent:(Event*)event
{
    //process obj for event
    Process* process = nil;
    
    //response
    CFOptionFlags response = 0;
    
    //dbg msg
    logMsg(LOG_DEBUG, [NSString stringWithFormat:@"processing queued event: %@", event]);
    
    //try find process object
    // ->ignore any events who's procs aren't found
    @synchronized(processList)
    {
        //lookup
        process = processList[event.processPath];
        if(nil == process)
        {
            //bail
            goto bail;
        }
    }
    
    //TODO: ignore apple procs!!
    
    //sync
    @synchronized(self.allowedProcs)
    {

    //skip events generated by 'user-allowed' processes
    if(YES == [self.allowedProcs[event.processID] isEqualToString:process.path])
    {
        //dbg msg
        logMsg(LOG_DEBUG, @"ignoring: is allowed process");
        
        //bail
        goto bail;
    }
        
    }//sync
    
    //dbg msg
    logMsg(LOG_DEBUG, @"2) is from non-allowed process");
    
    //sync
    @synchronized(self.disallowedProcs)
    {
    
    //skip events generated by disallowed processes
    // ->since a disallowed process is only set once user has killed (meaning such events are 'stale')
    if(YES == [self.disallowedProcs[event.processID] isEqualToString:process.path])
    {
        //dbg msg
        logMsg(LOG_DEBUG, @"ignoring: is disallowed process");
        
        //bail
        goto bail;
    }
    
    }//sync
        
    //dbg msg
    logMsg(LOG_DEBUG, @"3) is from non-disallowed process");
    
    //ignore files under 1KB
    if([[[NSFileManager defaultManager] attributesOfItemAtPath:event.filePath error:nil] fileSize] < 1024)
    {
        //dbg msg
        logMsg(LOG_DEBUG, [NSString stringWithFormat:@"ignoring: small file (%llu bytes)", [[[NSFileManager defaultManager] attributesOfItemAtPath:event.filePath error:nil] fileSize]]);
        
        //bail
        goto bail;
    }
    
    //dbg msg
    logMsg(LOG_DEBUG, @"4) is large enough");
    
    //skip any non-encrypted files
    if(YES != isEncrypted(event.filePath))
    {
        //dbg msg
        logMsg(LOG_DEBUG, @"ignoring: is not encrypted");
        
        //bail
        goto bail;
    }
    
    //dbg msg
    logMsg(LOG_DEBUG, @"5) is encrypted");
    
    //sync to alert user
    @synchronized(self)
    {
        //now sync'd
        // ->check again to ignore events that were prev alerted & disallowed by user!
        if(YES == [self.disallowedProcs[event.processID] isEqualToString:process.path])
        {
            //dbg msg
            logMsg(LOG_DEBUG, @"ignoring: is disallowed (now) process");
            
            //bail
            goto bail;
        }
        
        //dbg msg
        logMsg(LOG_DEBUG, @"suspending process and alerting user!");
        
        //suspend process
        if(-1 == kill(event.processID.intValue, SIGSTOP))
        {
            //failed to suspend process
            logMsg(LOG_ERR, [NSString stringWithFormat:@"failed to suspend %@ (%@), with %d", event.processID, event.processPath, errno]);
            
            //bail
            goto bail;
        }
        
        //alert user
        // ->note: will block until user responsed
        response = [self alertUser:event];
        
        //handle response
        // ->either resume or terminate process
        [self processResponse:event response:response];
    }
    
//bail
bail:
    
    return;
}


//show alert to the user
// ->block until response, which is returned from this method
-(CFOptionFlags)alertUser:(Event*)event
{
    //title
    
    //user's response
    CFOptionFlags response = 0;
    
    //header
    CFStringRef title = NULL;
    
    //body
    CFStringRef body = NULL;
    
    //init title
    title = (__bridge CFStringRef)([NSString stringWithFormat:@"RansomWhere: %@ 🔒'd a file", [event.processPath lastPathComponent]]);
   
    //init body
    body = (__bridge CFStringRef)([NSString stringWithFormat:@"%@\r\n\r\n🔒'd file: %@", event.processPath, event.filePath]);
    
    //show alert
    // ->will block until user iteraction, then response saved in 'response' variable
    CFUserNotificationDisplayAlert(0.0f, kCFUserNotificationStopAlertLevel, NULL, NULL, NULL, title, body, (__bridge CFStringRef)@"Terminate", (__bridge CFStringRef)@"Allow", NULL, &response);
    
//bail
bail:
    
    return response;
}

//handle response
// ->either resume or terminate process
-(void)processResponse:(Event*)event response:(CFOptionFlags)response
{
    //terminate process
    if(PROCESS_TERMINATE == response)
    {
        //dbg msg
        logMsg(LOG_DEBUG, @"user responded with: terminated");
        
        //terminate
        if(-1 == kill(event.processID.intValue, SIGKILL))
        {
            //err msg
            logMsg(LOG_ERR, [NSString stringWithFormat:@"failed to kill %@ (%@), with %d", event.processID, event.processPath, errno]);
            
            //bail
            goto bail;
        }
        
        //add to 'disallowed' procs set
        self.disallowedProcs[event.processID] = event.processPath;
        
        //dbg msg
        logMsg(LOG_DEBUG, @"terminated process");
    }
    
    //resume process
    else
    {
        //dbg msg
        logMsg(LOG_DEBUG, @"user responded with: resume (allow)");
        
        //resume
        if(-1 == kill(event.processID.intValue, SIGCONT))
        {
            //err msg
            logMsg(LOG_ERR, [NSString stringWithFormat:@"failed to resume %@ (%@), with %d", event.processID, event.processPath, errno]);
            
            //bail
            goto bail;
        }
        
        //add to 'allowed' procs set
        self.allowedProcs[event.processID] = event.processPath;
        
        //dbg msg
        logMsg(LOG_DEBUG, @"resumed process");
    }
    
//bail
bail:
 
    return;
}


@end
